config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.views.generic.base import TemplateView
from ocr import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    # path('common/', views.index),
    path('pybo/', include('pybo.urls')), # pybo/로 시작되는 페이지 요청은 모두 pybp/urls.py 파일에 있는 url매핑을 쓰란 말
    #path('pybo/', base_views.index, name='index'),  # '/' 에 해당되는 path /
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('upload/', views.upload, name='upload'),
    path('save-image/', views.save_detect, name='save_detect'),
    path('detect/', views.detect, name='detect'),
    path('cropimg/', TemplateView.as_view(template_name='cropimg.html'), name='cropimg'),
    path('transmit/', views.transmit, name='transmit')
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('',
        base_views.index, name='index'),
    path('<int:question_id>/',
        base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
        question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
        question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
        question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
        answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
        answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
        answer_views.answer_delete, name='answer_delete'),
]

pybo/models.py
from django.db import models
# from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
# pybo는 게시판을 만드는 거래
class Question(models.Model): # 질문 모델 작성
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # 계정이 삭제되면 질문도 삭제 
    subject = models.CharField(max_length=200) # 제목 최대 200자, max_length는 매개변수
    content = models.TextField() # 내용 
    create_date = models.DateTimeField() # 작성 일시 
    modify_date = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # 계정이 삭제되면 질문도 삭제 
    question = models.ForeignKey(Question, on_delete=models.CASCADE) # 질문이 삭제되면 답변도 삭제
    # 어떤 모델이 다른 모델의 속성을 이용하면 Foreignkey를 이용한다. 
    # cascade는 답변에 연결된 질문 삭제되면 답변도 삭제하라는 소리
    content = models.TextField() # 내용
    create_date = models.DateTimeField() # 작성일시
    modify_date = models.DateTimeField(null=True, blank=True)


# 모델을 변경한 후에는 반드시 makemigrations와 migrate를 통해 데이터베이스를 변경해 주어야 한다.  

pybo/forms.py
from django import forms
from pybo.models import Question, Answer

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class':'form-control', 'rows': 10}),
        # }
        labels = {
            'subject':'제목',
            'content':'내용',
        }
        
class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

pybo/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question, Answer

@login_required(login_url='common:login')
# 로그아웃 상태에서 @login_required 어노테이션이 적용된 함수가 호출되면 자동으로 로그인 화면으로 이동하게 된다
def answer_create(request, question_id):
    '''
    pybo 답변 등록
    '''
    question = get_object_or_404(Question, pk = question_id)
    # Django에서 Question 모델을 가진 데이터베이스에서 
    # question_id가 id인 Question 객체를 가져온다.
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user  # author 속성에 로그인 계정 저장
            answer.question = question
            answer.create_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else: # 이 else문은 젤 앞에 있는 if문꺼다 
        form = AnswerForm()
    context = {'question':question, 'form': form}

    return render(request, 'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from ..models import Question


# Create your views here.
def index(request):
    '''
    pybo 목록 출력
    '''
    # 입력인자
    page = request.GET.get('page','1') # 페이지
    # get방식 요청 >> localhost:8000/pybo/?page=1 이런식으로 뒤에 붙는 형식??
    
    # 조회
    question_list = Question.objects.order_by('-create_date')
    # Django에서 Question 모델을 가진 데이터베이스에서 
    # 모든 Question 객체를 create_date 속성의 역순으로 정렬하여 가져오는 쿼리셋을 생성합니다.
    
    # 페이징 처리
    paginator = Paginator(question_list, 10) # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    
    context = {'question_list': page_obj}
    # context 는 render에 인자로 보낼 데이터를 변수로 저장하는 것
    # question_list 뷰 함수에서는 Question 모델에서 조회한 데이터를 page_obj로 페이징 처리하여 context 변수에 담아서 
    # render 함수의 인자로 전달합니다. 이렇게 전달된 context 변수는 pybo/question_list.html 템플릿에서
    # question_list 변수로 사용될 수 있습니다.
    #즉, context 변수는 뷰 함수에서 처리한 데이터나 조회한 데이터를 템플릿에서 사용할 수 있도록 전달하는 역할을 합니다.
    
    # return HttpResponse("안녕하세요 pybo에 오신것을 환영합니다.")
    return render(request, 'pybo/question_list.html', context)
    # question_list를 pybo/question_list.html에 적용하여 html코드로 변환해줌 render~
    # 장고는 pybo/question_list.html이런 파일을 템플릿이라 한다.
    
def detail(request, question_id):
    '''
    pybo 내용 출력
    '''
    question = get_object_or_404(Question, pk = question_id)
    # Django에서 Question 모델을 가진 데이터베이스에서 
    # question_id가 id인 Question 객체를 가져온다.
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question

@login_required(login_url='common:login')
def question_create(request):
    """
    pybo 질문 등록
    """
    # form = QuestionForm()
    # return render(request, 'pybo/question_form.html', {'form': form})
    
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user  # author 속성에 로그인 계정 저장
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else: # 이 else문은 젤 앞에 있는 if문꺼다 
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()  # 수정일시 저장
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                    rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                {% if question.modify_date %}
            <div class="badge bg-light text-dark p-2 text-start mx-3">
                <div class="mb-2">modified at</div>
                <div>{{ question.modify_date }}</div>
            </div>
            {% endif %}
                
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ question.author.username }}</div>
                    <div>{{ question.create_date }}</div>
                    
                </div>
            </div>
            <div class="my-3">
                {% if request.user == question.author %}
                <a href="{% url 'pybo:question_modify' question.id  %}" 
                    class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
                    data-uri="{% url 'pybo:question_delete' question.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                {% if answer.modify_date %}
            <div class="badge bg-light text-dark p-2 text-start mx-3">
                <div class="mb-2">수정일자</div>
                <div>{{ answer.modify_date }}</div>
            </div>
            {% endif %}
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ answer.author.username }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
            <div class="my-3">
                {% if request.user == answer.author %}
                <a href="{% url 'pybo:answer_modify' answer.id  %}" 
                    class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#" class="delete btn btn-sm btn-outline-secondary "
                    data-uri="{% url 'pybo:answer_delete' answer.id  %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                        name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
</script>
{% endblock %}
{% comment %} 질문, 답변은 하나의 뭉치로 해당되므로 부트스트랩의 card 컴포넌트 사용하고  질문 내용과 답변 내용은
style속성으로 white-space: pre-line을 적용하여 텍스트의 줄바꿈을 정상적으로 보이게 만들었다. 부트스트랩 클래스 my-3은 상하 마진값 3을 의미한다. 
py-2는 상하 패딩값 2, p-2는 상하좌우 패딩값 2를 의미한다. d-flex justify-content-end는 컴포넌트 오른쪽 정렬을 뜻한다.{% endcomment %}
{% comment %} ---------------------------------------------------------------------------------- {% endcomment %}

{% comment %} <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<h1>{{ question.subject }}</h1>

<div>
    {{ question.content }}
</div>

<h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
<div>
    <ul>
    {% for answer in question.answer_set.all %}
        <li>{{ answer.content }}</li>
    {% endfor %}
    </ul>
</div>


<form action-"{% url 'pybo:answer_create' question.id %}" method="post">
{% csrf_token %}
<textarea name="content" id = "content" rows="15"></textarea>
<input type="submit" value="답변등록">
</form> {% endcomment %}

templates/pybo/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% comment %} {{ form.as_p }} <!-- form 엘리먼트와 입력 항목을 자동으로 생성해 주는는데 부트스트랩 안됨--> {% endcomment %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alret">
            {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
    {% endif %}
    <!-- 오류표시 end -->
    <div class="form-group">
        <label for='subject'>제목</label>
        <input type="text" class="form-control" name="subject" id="subject" 
        value="{{ form.subject.value|default_if_none:''}}">
    </div>
    <div class="form-group">
        <label for="content">내용</label>
        <textarea class="form-control" name="content" id="content"
        rows = "10">{{ form.content.value|default_if_none:''}}</textarea>
    </div>

        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
<div class="container my-3">
    <!-- 검색어를 입력할 수 있는 텍스트창(질문 등록하기) -->
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <!-- 자바 스크립트에서 이 텍스트창에 입력된 값을 읽기 위해 다음처럼 id 속성을 추가한 점에 주목 -->
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>

    <table class="table">
        <thead>        {% comment %} table head  {% endcomment %}
        <tr class="text-center table-dark">
            <th>번호</th>
            <th style="width:50%">제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr class="text-center">
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            {% comment %} <td>{{ forloop.counter }}</td> 이건 그냥 번호고 위에 있는게 페이지 별로 더해지는 번호 구현하는 코드 {% endcomment %}
            <td class="text-start">
                <a href="{% url 'pybo:detail' question.id %}">
                    {{ question.subject }}
                </a>
            </td>
            <td>{{ question.author.username }}</td>  <!-- 글쓴이 추가 -->
            <td>{{ question.create_date }}</td>
        <tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징 처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전 페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            {% comment %} <a class="page-link"
                href="?page={{ question_list.previous_page_number }}">
                이전
            </a> 일단 냅둬 {% endcomment %} 
            <a class="page-link" data-page="{{ question_list.previous_page_number }}"
                href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class='page-link' tabindex="-1" aria-disabled="true" href="#">
                이전
            </a>
        </li>
        {% endif %}
        <!-- 페이지 리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %} <!-- 책 -->
            {% if page_number in question_list.number%}
            <li class="page-item active" aria-current="page">
                {% comment %} <a class="page-link" href="?page={{ page_number }}">
                    {{ page_number }}
                </a> {% endcomment %}
                <a class="page-link" data-page="{{ page_number }}"
                    href="javascript:void(0)">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                {% comment %} <a class="page-link" href="?page={{ page_number }}">
                    {{ page_number }}
                </a> {% endcomment %}
                <a class="page-link" data-page="{{ page_number }}"
                    href="javascript:void(0)">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음 페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            {% comment %} <a class="page=link"
                href="?page={{ question_list.next_page_number }}">
                다음
            </a> {% endcomment %}
            <a class="page-link" data-page="{{ question_list.next_page_number }}"
                href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">
                다음
            </a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징 처리 끝 -->

    {% comment %} <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">
        질문 등록하기
    </a> 위에 질문 등록하기 다시 만듦 {% endcomment %}
</div>
<form id="searchForm" method="get" action="{% url 'home' %}">
    <!-- GET 방식으로 요청해야 하므로 method 속성에 "get"을 설정 -->
    <!-- action 속성은 '폼이 전송되는 URL'이므로 질문 목록 URL인 {% url 'index' %}를 지정 -->
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <!--  kw와 page는 이전에 요청했던 값을 기억하고 있어야 하므로 value에 값을 대입 -->
    <!-- 이전에 요청했던 kw와 page의 값은 index 함수로부터 전달될 것이다.-->
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}
{% comment %} ---------------------------------------------------------------------------------- {% endcomment %}

{% comment %} {% if question_list %} 
    <ul>
    {% for question in question_list %}
        <li><a href="{% url 'pybo:detail' question.id %}/">{{ question.subject }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}  {% endcomment %}

{% comment %} --------------------------------------------------------------------------- {% endcomment %}

{% comment %} {% %} <= 이렇게 생긴게 템플릿 태그 {% endcomment %}
{% comment %} {% if question_list %} 만약 퀘스트리스트가 있다면
    <ul>
    {% for question in question_list %} 퀘스트리스트를 반복하여 순차적으로 퀘스트레 대입해서
        <li><a href="/pybo/{{ question.id}}/">{{ question.subject }}</a></li> 
        for문에 의해 대입된 퀘스트 객체의 id와 subject를 출력 하라
    {% endfor %}
    </ul>
{% else %}
    <p>질문이 없습니다.</p>
{% endif %}  {% endcomment %}

{% comment %} 
for 문에서는 forloop 객체를 사용할 수 있는데
forloop.counter는 for문의 순서로 1부터 표시한다는 뜻
forloop.counter0는 for문의 순서로 0부터 표시한다는 뜻
forloop.first는 for문의 첫번째 순서인 경우 True라는 뜻
forloop.last는 for문의 마지막 순서인 경우 True라는 뜻
{% endcomment %}