common/urls.py
from django.urls import path 
from django.contrib.auth import views as auth_views
from . import views

# Django의 namespace 기능을 사용하기 위해 app_name 변수에 'common' 지정
app_name = 'common'
# URL 패턴에 대한 경로 및 뷰 함수 지정
urlpatterns = [
     # 로그인 페이지에 대한 URL 패턴
    # auth_views.LoginView를 사용하여 로그인 뷰 처리
    # template_name 인수로 common/login.html 템플릿 파일 사용
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    # 로그아웃 페이지에 대한 URL 패턴
    # auth_views.LogoutView를 사용하여 로그아웃 뷰 처리
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    # 회원 가입 페이지에 대한 URL 패턴
    # views.signup 뷰 함수를 사용하여 회원 가입 처리
    path('signup/', views.signup, name='signup'),
] 

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from django.views.generic.base import TemplateView
from ocr import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/', include('common.urls')),
    # path('common/', views.index),
    path('pybo/', include('pybo.urls')), # pybo/로 시작되는 페이지 요청은 모두 pybp/urls.py 파일에 있는 url매핑을 쓰란 말
    #path('pybo/', base_views.index, name='index'),  # '/' 에 해당되는 path /
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('upload/', views.upload, name='upload'),
    path('save-image/', views.save_detect, name='save_detect'),
    path('detect/', views.detect, name='detect'),
    path('cropimg/', TemplateView.as_view(template_name='cropimg.html'), name='cropimg'),
    path('transmit/', views.transmit, name='transmit')
]

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('',
        base_views.index, name='index'),
    path('<int:question_id>/',
        base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
        question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
        question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
        question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
        answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
        answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
        answer_views.answer_delete, name='answer_delete'),
]

common/models.py
from django.db import models
from datetime import datetime # 현재시각 집어넣기
from django.contrib.auth.models import AbstractUser #Django에서 제공하는 모델 클래스 사용자 인증(authentication)과 관련된 필드

# class UserManager(BaseUserManager):
#     def create_user(self, username, password=None, **kwargs):
#         user = self.model(username=username, **kwargs)
#         user.set_password(password)
#         user.save(using=self._db)
#         return user

#     def create_superuser(self, username, password, **kwargs):
#         user = self.create_user(username, password, **kwargs)
#         user.is_admin = True
#         user.save(using=self._db)
#         return user

class User(AbstractUser):
    username = models.CharField(max_length=30, unique=True)
    birth = models.DateField(default=datetime.today)
    email = models.EmailField()
    number = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    detail_address = models.CharField(max_length=100, null=True, blank=True)
    is_admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'username' #인증 시스템에서 사용자를 식별하기 위한 필드를 지정하는 클래스 변수

    # # objects = UserManager()

    # def __str__(self):
    #     return self.username

    # def has_perm(self, perm, obj=None):
    #     return True

    # def has_module_perms(self, app_label):
    #     return True

    # @property
    # def is_staff(self):
    #     return self.is_admin

common/forms.py
from django import forms # 장고에서 form 모듈 가져오기
from django.contrib.auth.forms import UserCreationForm # 장고가 제공하는 기본적인 회원가입을 위한 폼
from .models import User

# 웹 애플리케이션에서 사용자로부터 입력을 받을 때, 
# 입력값의 유효성 검사나 처리를 위해서 사용되는 것을 '폼(Form)'이라고 합니다.

class UserForm(UserCreationForm): # 장고가 제공하는 usercreationform을 상속받아서 user 모델 이용
    birth = forms.DateField(label="생년월일")
    email = forms.EmailField(label="이메일")
    number = forms.CharField(label="전화번호")
    address = forms.CharField(label="주소")
    detail_address = forms.CharField(label="상세주소")
    

    class Meta: # 폼에서 사용하는 모델과 필드를 지정 
        model = User
        fields = ["username", "birth", "password1", "password2", "email", "number", "address","detail_address"]
        labels = {
            'username':'제목',
            'birth':'생년월일',
            'password1':'비밀번호',
            'password2':'비밀번호_확인',
            'email':'이메일',
            'number':'전화번호',
            'address':'주소',
            'detail_address':'상세주소',
            
        }
        # meta데이터안에서 라벨 지정하면 다른 폼에서도 동일한 라벨을 사용할 수 있다.

common/views.py
from django.shortcuts import render, redirect # Django에서 제공하는 함수들을 불러옵니다.
# from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, login # Django에서 제공하는 인증 관련 함수들을 불러옵니다.
from common.models import User # User 모델을 불러옵니다.
from common.forms import UserForm # UserForm 폼을 불러옵니다.
 

from django.contrib.auth.hashers import make_password # 비밀번호 해싱을 위한 함수를 불러옵니다.

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST) # UserForm에서 클라이언트가 보낸 데이터를 가져옵니다.
        if form.is_valid(): # 폼형식이 맞으면 
            # 폼에서 입력받은 데이터를 새로운 User 모델 객체에 저장
            user = User(
                username=form.cleaned_data.get('username'),
                password=make_password(form.cleaned_data.get('password1')),  # 비밀번호 해싱
                birth=form.cleaned_data.get('birth'),
                email=form.cleaned_data.get('email'),
                number=form.cleaned_data.get('number'),
                address=form.cleaned_data.get('address'),
                detail_address=form.cleaned_data.get('detail_address'),
            )
            user.set_password(form.cleaned_data.get('password1')) # 비밀번호 설정
            user.save()  # User 모델 객체를 데이터베이스에 저장합니다.

            # 사용자 인증 및 로그인
            authenticate_and_login(request, user) # 사용자를 인증하고 로그인합니다.

            return redirect('home') # 회원가입이 완료되면 'home'으로 이동합니다.
    else:
        form = UserForm() # 클라이언트가 GET 요청을 보낸 경우, 빈 회원가입 폼을 생성합니다.
    return render(request, 'common/signup-index.html', {'form': form}) # 회원가입 폼을 렌더링하여 반환합니다.

def authenticate_and_login(request, user):
    # 입력받은 정보를 인증하고 로그인을 시도함
    authenticated_user = authenticate(request, username=user.username, password=request.POST['password1'])
    if authenticated_user is not None: # 사용자 인증에 성공한 경우
        login(request, authenticated_user) # 로그인
        
        
'''
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            # 폼에서 입력받은 데이터를 새로운 User 모델 객체에 저장
            user = User(
                username=form.cleaned_data.get('username'),
                password=make_password(form.cleaned_data.get('password1')),  # 비밀번호 해싱
                birth=form.cleaned_data.get('birth'),
                email=form.cleaned_data.get('email'),
                number=form.cleaned_data.get('number'),
                address=form.cleaned_data.get('address'),
                detail_address=form.cleaned_data.get('detail_address'),
            )
            user.save()  # 저장

            # 사용자 인증 및 로그인
            user = authenticate(request, username=user.username, password=user.password)
            login(request, user)

            return redirect('home')
    else:
        form = UserForm()
    return render(request, 'common/signup-index.html', {'form': form})
'''

templates/common/(수정전)login.html
{% extends "base.html" %}
{% block content %}


<div class="container my-3">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                    value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                    value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/common/login.html
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/53a8c415f1.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../../static/sign-in-css/sign-in.css">

    
</head>

<body>
    
        <form method="post" action="{% url 'common:login' %}">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{ next }}">  <!-- 로그인 성공후 이동되는 URL -->
            {% comment %} {% include "form_errors.html" %}  {% endcomment %} <!--팝업창으로변경 -->
        <div class="wrap">
        <div class="login">
            <h2>Log-in</h2>
            <div class="login_sns">
            <!-- <li><a href=""><i class="fab fa-instagram"></i></a></li>
            <li><a href=""><i class="fab fa-facebook-f"></i></a></li>
            <li><a href=""><i class="fab fa-twitter"></i></a></li> -->
            </div>
            <div class="login_id">
                <h4>사용자ID</h4>
                <input type="text" name="username" id="username" placeholder="username"
                value="{{ form.username.value|default_if_none:'' }}">
            </div>
            <div class="login_pw">
                <h4>Password</h4>
                <input type="password" name="password" id="password" placeholder="Password"
                value="{{ form.password.value|default_if_none:'' }}">
            </div>
            <div class="submit">
                <input type="submit" value="login">
            </div>

            <div class="button">
                <input type="button" class="button" id="signup" value="Sign up" onclick="location.href='{% url 'common:signup' %}'">

            </div>

            <!-- 모달 팝업창 추가함 -->
            <div id="error-modal" class="modal">
                <div class="modal-content">
                {% comment %} <span class="close">&times;</span> {% endcomment %}
                <div class="modal-body">
                    {% if form.errors %}
                    <div class="alert alert-danger">
                    {% for field in form %}
                    {% if field.errors %}
                    <div>
                        <strong>{{ field.label }}</strong>
                        {{ field.errors }}
                    </div>
                    {% endif %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                    <div>
                        <strong>{{ error }}</strong>
                    </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}


<!-- 모달 팝업 구동하기위해서 사용하는 JavaScript 코드 추가함.-->
{% block scripts %}
<script src="{% static 'static\error\error.js' %}"></script>
{% endblock %}

templates/common/signup-index.html
{% block content %}
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>회원가입 창</title>

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <link rel="JavaScript" href="../../static/phonenumber/phonenumber.js">

  <script>
    function addHyphen(element) {
        let ele = element.value.split('-').join('');    // '-' 제거
        if (ele.length > 3) {
        ele = ele.substring(0, 3) + '-' + ele.substring(3);
        }
        if (ele.length > 8) {
        ele = ele.substring(0, 8) + '-' + ele.substring(8);
        }
        element.value = ele;
        }
    </script>

  <style>
    body {
      min-height: 100vh;

      background: -webkit-gradient(linear, left bottom, right top, from(#5AD18F), to(#1d466c));
      background: -webkit-linear-gradient(bottom left, #5AD18F 0%, #1d466c 100%);
      background: -moz-linear-gradient(bottom left, #5AD18F 0%, #1d466c 100%);
      background: -o-linear-gradient(bottom left, #5AD18F 0%, #1d466c 100%);
      background: linear-gradient(to top right, #5AD18F 0%, #1d466c 100%);
    }

    .input-form {
      max-width: 680px;

      margin-top: 80px;
      padding: 32px;

      background: #ffffff;
      -webkit-border-radius: 10px;
      -moz-border-radius: 10px;
      border-radius: 10px;
      -webkit-box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15);
      -moz-box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15);
      box-shadow: 0 8px 20px 0 rgba(0, 0, 0, 0.15)
    }
    h1 {
      margin-top: 50px; /* 아래로 내리기 */
      text-align: center; /* 가운데 정렬 */
    }
    
  </style>









</head>


<body>

<!-- Header -->
<header id="header">
  <h1><a class="text-center mb-5 text-white" href="{% url 'home' %}">Menu 'I'</a></h1>

  <nav class="main">
  </nav>
</header>



  <div class="container">
    <form method="post" action="{% url 'common:signup' %}">
      {% csrf_token %}
      {% include "form_errors.html" %}
    <div class="input-form-backgroud row">
      <div class="input-form col-md-12 mx-auto">
        <h4 class="mb-3">회원가입</h4>
        {% comment %} <form class="validation-form" novalidate>{% endcomment %}

          <div class="row">
            <div class="col-md-6 mb-3">
              <label for="username">이름</label>
              <input type="text" class="form-control" id="username" name="username" placeholder="" 
              value="{{ form.username.value|default_if_none:'' }}" required>
              <div class="invalid-feedback">
                이름을 입력해주세요.
              </div>
            </div>

            <div class="col-md-6 mb-3">
              <label for="birth">생년월일</label>
              <input type="date" class="form-control" id="birth" name="birth" placeholder="" 
              value="{{ form.birth.value|default_if_none:'' }}" required>
              <div class="invalid-feedback">
                생년월일을 입력해주세요.
              </div>
            </div>
          </div>

          <div class="row">
            <div class="col-md-6 mb-3">
              <label for="password1">비밀번호</label>
              <input type="password" class="form-control" id="password1" name="password1" placeholder="" 
              value="{{ form.password1.value|default_if_none:'' }}" required>
              <div class="invalid-feedback">
                비밀번호을 입력해주세요.
              </div>
            </div>
            
            <div class="col-md-6 mb-3">
              <label for="password2">비밀번호 확인</label>
              <input type="password" class="form-control" id="password2" name="password2" placeholder="" 
              value="{{ form.password2.value|default_if_none:'' }}" required>
              <div class="invalid-feedback">
                비밀번호 확인을 입력해주세요.
              </div>
            </div>
          </div>

          <div class="mb-3">
            <label for="email">이메일</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="you@example.com" 
            value="{{ form.email.value|default_if_none:'' }}" required>
            <div class="invalid-feedback">
              이메일을 입력해주세요.
            </div>
          </div>

          <div class="mb-3">
            <label for="number">전화번호</label>
            <input type="text" class="form-control" id="number" name="number" 
            placeholder="xxx-xxxx-xxxx" maxlength="13" onkeyup="addHyphen(this)"
            value="{{ form.number.value|default_if_none:'' }}" required>
            <div class="invalid-feedback">
              전화번호를 입력해주세요.
            </div>
          </div>
          
          
          <div class="mb-3">
            <label for="address">주소</label>
            <input type="text" class="form-control" id="address" name="address" 
            value="{{ form.address.value|default_if_none:'' }}"
            placeholder="서울특별시 강남구" required>
            <div class="invalid-feedback">
              주소를 입력해주세요.
            </div>
          </div>
          <button type="button" class="btn btn-primary btn-lg btn-block" onclick="openDaumAddressPopup()">주소 검색</button><br>
        

          <div class="mb-3">
            <label for="detail_address">상세주소</label>
            <input type="text" class="form-control" 
            id="detail_address" name="detail_address"
            placeholder="상세주소를 입력해주세요."
            value="{{ form.detail_address.value|default_if_none:'' }}">
          </div>

          <hr class="mb-4">
          <div class="custom-control custom-checkbox">
            <input type="checkbox" class="custom-control-input" id="aggrement" required>
            <label class="custom-control-label" for="aggrement">개인정보 수집 및 이용에 동의합니다.</label>
          </div>
          <div class="mb-4"></div>
          <button class="btn btn-primary btn-lg btn-block" type="submit">가입 완료</button>
        </form>
      </div>
    </div>
    <footer class="my-3 text-center text-small">
      <p class="mb-1">&copy; 2023 menu ' i '</p>
    </footer>
  </div>


  <script src="https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js"></script>
  <script>
      function openDaumAddressPopup() {
          new daum.Postcode({
              oncomplete: function(data) {
                  document.getElementById('address').value = data.address;
              }
          }).open();
      }
  </script>




  <script>
    window.addEventListener('load', () => {
      const forms = document.getElementsByClassName('validation-form');

      Array.prototype.filter.call(forms, (form) => {
        form.addEventListener('submit', function (event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }

          form.classList.add('was-validated');
        }, false);
      });
    }, false);
  </script>
  {% endblock %}
{% comment %} </body>

</html> {% endcomment %}